import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'hi' | 'en' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'pa';

export const languageNames: Record<Language, string> = {
  hi: 'हिन्दी',
  en: 'English',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  bn: 'বাংলা',
  mr: 'मराठी',
  gu: 'ગુજરાતી',
  pa: 'ਪੰਜਾਬੀ',
};

type TranslationKey = string;
type Translations = Record<Language, Record<TranslationKey, string>>;

const translations: Translations = {
  en: {
    'nav.home': 'Home',
    'nav.order': 'Order Now',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'hero.badge': 'Trusted Ayurvedic Medicine',
    'hero.title': 'Suffering from Piles, Warts & Fistula?',
    'hero.subtitle': 'Ayurvedic treatment without surgery',
    'hero.cta': 'Order Now',
    'hero.ayurvedic': '100% Ayurvedic',
    'hero.patients': '3.5 Lakh+ Patients',
    'hero.experience': '10+ Years Experience',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'What is Piles, Warts & Fistula?',
    'problem.subtitle': 'Understand the problem to find the right solution',
    'problem.piles': 'Piles (Bawaseer)',
    'problem.pilesDesc': 'Swollen veins around the anus causing pain, burning and bleeding.',
    'problem.massa': 'Warts (Massa)',
    'problem.massaDesc': 'Small flesh growth outside the anus causing pain while sitting.',
    'problem.fistula': 'Fistula (Bhagandhar)',
    'problem.fistulaDesc': 'A wound or passage near the anus causing pus and pain.',
    'problem.symptoms': 'Common Symptoms',
    'problem.sym1': 'Pain during bowel movement',
    'problem.sym2': 'Bleeding',
    'problem.sym3': 'Burning & itching',
    'problem.sym4': 'Swelling',
    'causes.title': 'Main Causes of Piles',
    'causes.cause1': 'Constipation',
    'causes.cause2': 'Spicy food',
    'causes.cause3': 'Sitting for long hours',
    'causes.cause4': 'Drinking less water',
    'causes.cause5': 'Poor digestion',
    'solution.title': 'Earth Ayurvedic\'s Natural Solution',
    'solution.combo': 'Powerful Ayurvedic Combination',
    'solution.pills': 'Herbal Pills',
    'solution.syrup': 'Ayurvedic Syrup',
    'solution.powder': 'Constipation Powder',
    'solution.b1': 'Helps stop bleeding',
    'solution.b2': 'Helps dry out piles',
    'solution.b3': 'Relief from pain & burning',
    'solution.b4': 'Helps improve digestion',
    'benefits.title': 'Key Benefits',
    'benefits.pain': 'Quick pain relief',
    'benefits.bleeding': 'Stops bleeding',
    'benefits.burning': 'Reduces burning',
    'benefits.itching': 'Stops itching',
    'benefits.pus': 'Stops discharge',
    'benefits.dryout': 'Dries out piles',
    'benefits.lumps': 'Reduces lumps',
    'benefits.constipation': 'Relieves constipation',
    'treat.title': 'Choose the Right Treatment',
    'treat.opt1Title': '₹1000 Treatment',
    'treat.opt1Sub': 'For patients WITHOUT constipation',
    'treat.opt2Title': '₹1300 Complete Treatment',
    'treat.opt2Sub': 'For patients WITH constipation',
    'treat.herbalPills': 'Herbal Pills',
    'treat.ayurvedicSyrup': 'Ayurvedic Syrup',
    'treat.constPowder': 'Constipation Powder',
    'treat.helpBleeding': 'Bleeding',
    'treat.helpPain': 'Pain',
    'treat.helpSwelling': 'Piles swelling',
    'treat.helpConstipation': 'Constipation',
    'treat.helpPiles': 'Piles',
    'treat.includes': 'Includes',
    'treat.helpsIn': 'Helps with',
    'treat.codAvailable': 'Cash on Delivery',
    'treat.recommended': 'Recommended',
    'howto.title': 'How to Use Medicine',
    'howto.pills.title': 'Pills',
    'howto.pills.desc': 'Take 1 pill in the morning and 1 pill at night daily before meals. Consume with lukewarm water.',
    'howto.syrup.title': 'Syrup',
    'howto.syrup.desc': 'Take 10 ml syrup once daily at night before sleep. You can take it with normal or lukewarm water.',
    'howto.powder.title': 'Powder',
    'howto.powder.desc': 'If you have constipation, take 1 teaspoon powder at night before sleep. Mix with lukewarm water and drink.',
    'effect.title': 'Medicine Effect Duration',
    'effect.week1': 'First 3-7 Days',
    'effect.week1desc': 'May help reduce pain, burning and itching. Helps improve bowel movement.',
    'effect.week2': '7-14 Days',
    'effect.week2desc': 'Helps reduce bleeding and swelling. Sitting discomfort may start improving.',
    'effect.week3': '2-4 Weeks',
    'effect.week3desc': 'Piles lumps may start shrinking gradually. Relief from constipation.',
    'effect.week4': '4-8 Weeks (Regular Use)',
    'effect.week4desc': 'Overall improvement in piles symptoms. Maintains digestive health.',
    'trust.title': 'Why Choose Earth Ayurvedic?',
    'trust.patients': 'Patients Treated',
    'trust.years': 'Years Experience',
    'trust.satisfaction': 'Satisfaction Rate',
    'trust.ayurvedic': 'Ayurvedic',
    'diet.title': 'What to Eat & What to Avoid',
    'diet.eat': 'What to Eat',
    'diet.avoid': 'What to Avoid',
    'diet.eat1': 'High fiber foods (fruits, vegetables)',
    'diet.eat2': 'Drink plenty of water (8-10 glasses)',
    'diet.eat3': 'Whole grains and brown rice',
    'diet.eat4': 'Papaya, banana, seasonal fruits',
    'diet.eat5': 'Green leafy vegetables',
    'diet.eat6': 'Buttermilk and curd',
    'diet.avoid1': 'Spicy and oily food',
    'diet.avoid2': 'Junk food and fast food',
    'diet.avoid3': 'Red meat',
    'diet.avoid4': 'Excessive tea and coffee',
    'diet.avoid5': 'Alcohol and smoking',
    'diet.avoid6': 'Refined flour (maida) products',
    'stats.patients': 'Successful Patients',
    'stats.years': 'Years of Trust',
    'stats.delivery': 'Cities Delivered',
    'stats.satisfaction': 'Satisfaction Rate',
    'reviews.title': 'What Our Patients Say',
    'whatsapp.reviews': 'WhatsApp Reviews',
    'certificates.title': 'Certified & Verified',
    'reels.title': 'Watch Our Patient Stories',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'Is this medicine safe?',
    'faq.a1': 'Yes, it is 100% Ayurvedic and made from natural herbs. It is completely safe.',
    'faq.q2': 'How many days to see results?',
    'faq.a2': 'Improvement is usually felt in 7-15 days with regular use.',
    'faq.q3': 'Is COD available?',
    'faq.a3': 'Yes, Cash on Delivery is available across India.',
    'faq.q4': 'Can women use this medicine?',
    'faq.a4': 'Yes, this medicine is safe for both men and women. Pregnant women should consult a doctor first.',
    'faq.q5': 'Do I need all 3 medicines?',
    'faq.a5': 'If you have constipation, the complete package (₹1300) is recommended. Otherwise, Pills + Syrup (₹1000) is sufficient.',
    'ordercta.title': 'Ready to Get Relief?',
    'ordercta.subtitle': 'Choose your treatment and order now with Cash on Delivery',
    'order.title': 'Order Now',
    'order.name': 'Full Name',
    'order.phone': 'Phone Number',
    'order.address': 'Full Address',
    'order.city': 'City',
    'order.state': 'State',
    'order.pincode': 'PIN Code',
    'order.package': 'Select Package',
    'order.pkg1': 'Pills + Syrup - ₹1000',
    'order.pkg2': 'Pills + Syrup + Powder - ₹1300',
    'order.submit': 'Place Order',
    'order.cod': 'Cash on Delivery',
    'order.free': 'Free Home Delivery',
    'footer.disclaimer': 'This is an Ayurvedic product. Results may vary based on individual conditions. Consult a doctor for serious conditions.',
    'important.info': 'Important Information',
    'constipation.title': 'Role of Constipation in Piles',
    'constipation.desc': 'Constipation is the root cause of most piles problems.',
    'm2': 'Take this combo only if you have constipation',
  },
  hi: {
    'nav.home': 'होम',
    'nav.order': 'ऑर्डर करें',
    'nav.reviews': 'समीक्षा',
    'nav.contact': 'संपर्क',
    'hero.badge': 'विश्वसनीय आयुर्वेदिक दवा',
    'hero.title': 'बवासीर, मस्सा और भगंदर से परेशान हैं?',
    'hero.subtitle': 'बिना ऑपरेशन के आयुर्वेदिक इलाज',
    'hero.cta': 'अभी ऑर्डर करें',
    'hero.ayurvedic': '100% आयुर्वेदिक',
    'hero.patients': '3.5 लाख+ मरीज़',
    'hero.experience': '10+ साल का अनुभव',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'बवासीर, मस्सा और भगंदर क्या है?',
    'problem.subtitle': 'समस्या को समझें ताकि सही समाधान मिल सके',
    'problem.piles': 'बवासीर (Piles)',
    'problem.pilesDesc': 'गुदा के आसपास सूजी हुई नसें जिससे दर्द, जलन और ब्लीडिंग होती है।',
    'problem.massa': 'मस्सा (Hemorrhoid Mass)',
    'problem.massaDesc': 'गुदा के बाहर मांस का छोटा उभार जिससे बैठने में दर्द होता है।',
    'problem.fistula': 'भगंदर (Fistula)',
    'problem.fistulaDesc': 'गुदा के पास घाव या रास्ता बन जाना जिससे मवाद और दर्द होता है।',
    'problem.symptoms': 'सामान्य लक्षण',
    'problem.sym1': 'मल त्याग में दर्द',
    'problem.sym2': 'खून आना',
    'problem.sym3': 'जलन और खुजली',
    'problem.sym4': 'सूजन',
    'causes.title': 'बवासीर होने के मुख्य कारण',
    'causes.cause1': 'कब्ज',
    'causes.cause2': 'मसालेदार भोजन',
    'causes.cause3': 'लंबे समय तक बैठना',
    'causes.cause4': 'कम पानी पीना',
    'causes.cause5': 'पाचन खराब होना',
    'solution.title': 'Earth Ayurvedic का प्राकृतिक समाधान',
    'solution.combo': 'शक्तिशाली आयुर्वेदिक संयोजन',
    'solution.pills': 'हर्बल गोलियां',
    'solution.syrup': 'औषधीय सिरप',
    'solution.powder': 'कब्ज पाउडर',
    'solution.b1': 'ब्लीडिंग रोकने में मदद',
    'solution.b2': 'मस्से सुखाने में सहायक',
    'solution.b3': 'दर्द और जलन में राहत',
    'solution.b4': 'पाचन सुधारने में मदद',
    'benefits.title': 'मुख्य फायदे',
    'benefits.pain': 'दर्द में तुरंत राहत',
    'benefits.bleeding': 'ब्लीडिंग रोके',
    'benefits.burning': 'जलन कम करे',
    'benefits.itching': 'खुजली रोके',
    'benefits.pus': 'डिस्चार्ज रोके',
    'benefits.dryout': 'मस्से सुखाए',
    'benefits.lumps': 'गांठ कम करे',
    'benefits.constipation': 'कब्ज में राहत',
    'treat.title': 'सही इलाज चुनें',
    'treat.opt1Title': '₹1000 का इलाज',
    'treat.opt1Sub': 'बिना कब्ज वाले मरीजों के लिए',
    'treat.opt2Title': '₹1300 पूरा इलाज',
    'treat.opt2Sub': 'कब्ज वाले मरीजों के लिए',
    'treat.herbalPills': 'हर्बल गोलियां',
    'treat.ayurvedicSyrup': 'आयुर्वेदिक सिरप',
    'treat.constPowder': 'कब्ज पाउडर',
    'treat.helpBleeding': 'ब्लीडिंग',
    'treat.helpPain': 'दर्द',
    'treat.helpSwelling': 'बवासीर की सूजन',
    'treat.helpConstipation': 'कब्ज',
    'treat.helpPiles': 'बवासीर',
    'treat.includes': 'शामिल है',
    'treat.helpsIn': 'मदद करता है',
    'treat.codAvailable': 'कैश ऑन डिलीवरी',
    'treat.recommended': 'सुझावित',
    'howto.title': 'दवाई कैसे उपयोग करें',
    'howto.pills.title': 'गोलियां',
    'howto.pills.desc': 'रोज़ सुबह 1 गोली और रात को 1 गोली खाना खाने से पहले लें। गुनगुने पानी के साथ सेवन करें।',
    'howto.syrup.title': 'सिरप',
    'howto.syrup.desc': 'रात को सोने से पहले 10 ml सिरप लें। ज़रूरत हो तो सादे या गुनगुने पानी के साथ ले सकते हैं।',
    'howto.powder.title': 'पाउडर',
    'howto.powder.desc': 'अगर कब्ज है तो रात को सोने से पहले 1 चम्मच पाउडर लें। गुनगुने पानी में मिलाकर पिएं।',
    'effect.title': 'दवाई का प्रभाव अवधि',
    'effect.week1': 'पहले 3-7 दिन',
    'effect.week1desc': 'दर्द, जलन और खुजली कम होने में मदद। मल त्याग में सुधार।',
    'effect.week2': '7-14 दिन',
    'effect.week2desc': 'ब्लीडिंग और सूजन कम होने में मदद। बैठने में तकलीफ कम होने लगती है।',
    'effect.week3': '2-4 सप्ताह',
    'effect.week3desc': 'मस्से धीरे-धीरे कम होने लगते हैं। कब्ज और जलन में राहत।',
    'effect.week4': '4-8 सप्ताह (नियमित उपयोग)',
    'effect.week4desc': 'बवासीर के लक्षणों में समग्र सुधार। पाचन स्वास्थ्य बनाए रखने में मदद।',
    'trust.title': 'क्यों चुनें Earth Ayurvedic?',
    'trust.patients': 'इलाज किए मरीज़',
    'trust.years': 'साल का अनुभव',
    'trust.satisfaction': 'संतुष्टि दर',
    'trust.ayurvedic': 'आयुर्वेदिक',
    'diet.title': 'क्या खाएं और क्या न खाएं',
    'diet.eat': 'क्या खाएं',
    'diet.avoid': 'क्या न खाएं',
    'diet.eat1': 'फाइबर युक्त भोजन (फल, सब्जियां)',
    'diet.eat2': 'भरपूर पानी पिएं (8-10 गिलास)',
    'diet.eat3': 'साबुत अनाज और ब्राउन राइस',
    'diet.eat4': 'पपीता, केला और मौसमी फल',
    'diet.eat5': 'हरी पत्तेदार सब्जियां',
    'diet.eat6': 'छाछ और दही',
    'diet.avoid1': 'मसालेदार और तैलीय भोजन',
    'diet.avoid2': 'जंक फूड और फास्ट फूड',
    'diet.avoid3': 'लाल मांस',
    'diet.avoid4': 'अधिक चाय और कॉफी',
    'diet.avoid5': 'शराब और धूम्रपान',
    'diet.avoid6': 'मैदे से बनी चीजें',
    'stats.patients': 'सफल मरीज़',
    'stats.years': 'साल का भरोसा',
    'stats.delivery': 'शहरों में डिलीवरी',
    'stats.satisfaction': 'संतुष्टि दर',
    'reviews.title': 'हमारे मरीज़ क्या कहते हैं',
    'whatsapp.reviews': 'WhatsApp समीक्षाएं',
    'certificates.title': 'प्रमाणित और सत्यापित',
    'reels.title': 'हमारे मरीज़ों की कहानियां देखें',
    'faq.title': 'अक्सर पूछे जाने वाले सवाल',
    'faq.q1': 'क्या यह दवा सुरक्षित है?',
    'faq.a1': 'हाँ, यह 100% आयुर्वेदिक है और प्राकृतिक जड़ी-बूटियों से बनी है। यह पूरी तरह सुरक्षित है।',
    'faq.q2': 'कितने दिन में असर दिखेगा?',
    'faq.a2': 'नियमित उपयोग से 7-15 दिनों में सुधार महसूस होता है।',
    'faq.q3': 'क्या COD उपलब्ध है?',
    'faq.a3': 'हाँ, Cash on Delivery पूरे भारत में उपलब्ध है।',
    'faq.q4': 'क्या महिलाएं इस दवा का उपयोग कर सकती हैं?',
    'faq.a4': 'हाँ, यह दवा पुरुषों और महिलाओं दोनों के लिए सुरक्षित है। गर्भवती महिलाएं पहले डॉक्टर से सलाह लें।',
    'faq.q5': 'क्या मुझे तीनों दवाएं चाहिए?',
    'faq.a5': 'अगर आपको कब्ज है तो पूरा पैकेज (₹1300) सुझावित है। अन्यथा गोलियां + सिरप (₹1000) पर्याप्त है।',
    'ordercta.title': 'राहत पाने के लिए तैयार हैं?',
    'ordercta.subtitle': 'अपना इलाज चुनें और Cash on Delivery से ऑर्डर करें',
    'order.title': 'अभी ऑर्डर करें',
    'order.name': 'पूरा नाम',
    'order.phone': 'फोन नंबर',
    'order.address': 'पूरा पता',
    'order.city': 'शहर',
    'order.state': 'राज्य',
    'order.pincode': 'पिन कोड',
    'order.package': 'पैकेज चुनें',
    'order.pkg1': 'गोलियां + सिरप - ₹1000',
    'order.pkg2': 'गोलियां + सिरप + पाउडर - ₹1300',
    'order.submit': 'ऑर्डर करें',
    'order.cod': 'कैश ऑन डिलीवरी',
    'order.free': 'फ्री होम डिलीवरी',
    'footer.disclaimer': 'यह एक आयुर्वेदिक उत्पाद है। परिणाम व्यक्ति की शारीरिक स्थिति के अनुसार अलग-अलग हो सकते हैं। किसी गंभीर समस्या की स्थिति में चिकित्सक की सलाह अवश्य लें।',
    'important.info': 'महत्वपूर्ण जानकारी',
    'constipation.title': 'बवासीर में कब्ज की भूमिका',
    'constipation.desc': 'कब्ज अधिकांश बवासीर समस्याओं का मूल कारण है।',
    'm2':'यह कॉम्बो केवल तब लें जब आपको कब्ज हो',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.order': 'ஆர்டர் செய்யுங்கள்',
    'nav.reviews': 'மதிப்பாய்வுகள்',
    'nav.contact': 'தொடர்பு',
    'hero.badge': 'நம்பகமான ஆயுர்வேத மருந்து',
    'hero.title': 'பைல்ஸ், மருக்கள் மற்றும் பிஸ்துலா பிரச்சனையா?',
    'hero.subtitle': 'அறுவை சிகிச்சை இல்லாமல் ஆயுர்வேத சிகிச்சை',
    'hero.cta': 'இப்போது ஆர்டர் செய்யுங்கள்',
    'hero.ayurvedic': '100% ஆயுர்வேதம்',
    'hero.patients': '3.5 லட்சம்+ நோயாளிகள்',
    'hero.experience': '10+ ஆண்டுகள் அனுபவம்',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'பைல்ஸ், மருக்கள் மற்றும் பிஸ்துலா என்றால் என்ன?',
    'problem.subtitle': 'சரியான தீர்வு கண்டறிய பிரச்சனையை புரிந்து கொள்ளுங்கள்',
    'problem.piles': 'பைல்ஸ்',
    'problem.pilesDesc': 'ஆசனவாய் சுற்றி வீங்கிய நரம்புகள் வலி, எரிச்சல் மற்றும் இரத்தப்போக்கு ஏற்படுத்தும்.',
    'problem.massa': 'மருக்கள்',
    'problem.massaDesc': 'ஆசனவாய் வெளியே சிறிய சதை வளர்ச்சி உட்காரும்போது வலி.',
    'problem.fistula': 'பிஸ்துலா',
    'problem.fistulaDesc': 'ஆசனவாய் அருகில் புண் அல்லது பாதை உருவாகுதல் சீழ் மற்றும் வலி.',
    'problem.symptoms': 'பொதுவான அறிகுறிகள்',
    'problem.sym1': 'மலம் கழிக்கும்போது வலி',
    'problem.sym2': 'இரத்தப்போக்கு',
    'problem.sym3': 'எரிச்சல் மற்றும் அரிப்பு',
    'problem.sym4': 'வீக்கம்',
    'causes.title': 'பைல்ஸ் ஏற்படும் முக்கிய காரணங்கள்',
    'causes.cause1': 'மலச்சிக்கல்',
    'causes.cause2': 'காரமான உணவு',
    'causes.cause3': 'நீண்ட நேரம் உட்காருதல்',
    'causes.cause4': 'குறைவாக தண்ணீர் குடிப்பது',
    'causes.cause5': 'செரிமானக் கோளாறு',
    'solution.title': 'Earth Ayurvedic இயற்கை தீர்வு',
    'solution.combo': 'சக்திவாய்ந்த ஆயுர்வேத கலவை',
    'solution.pills': 'மூலிகை மாத்திரைகள்',
    'solution.syrup': 'ஆயுர்வேத சிரப்',
    'solution.powder': 'மலச்சிக்கல் பொடி',
    'solution.b1': 'இரத்தப்போக்கை நிறுத்த உதவும்',
    'solution.b2': 'பைல்ஸை உலர்த்த உதவும்',
    'solution.b3': 'வலி மற்றும் எரிச்சலில் நிவாரணம்',
    'solution.b4': 'செரிமானத்தை மேம்படுத்த உதவும்',
    'benefits.title': 'முக்கிய நன்மைகள்',
    'benefits.pain': 'வலி நிவாரணம்',
    'benefits.bleeding': 'இரத்தப்போக்கு நிறுத்தும்',
    'benefits.burning': 'எரிச்சல் குறைக்கும்',
    'benefits.itching': 'அரிப்பு நிறுத்தும்',
    'benefits.pus': 'சீழ் நிறுத்தும்',
    'benefits.dryout': 'பைல்ஸ் உலர்த்தும்',
    'benefits.lumps': 'கட்டிகள் குறைக்கும்',
    'benefits.constipation': 'மலச்சிக்கல் நிவாரணம்',
    'treat.title': 'சரியான சிகிச்சையை தேர்வு செய்யுங்கள்',
    'treat.opt1Title': '₹1000 சிகிச்சை',
    'treat.opt1Sub': 'மலச்சிக்கல் இல்லாத நோயாளிகளுக்கு',
    'treat.opt2Title': '₹1300 முழுமையான சிகிச்சை',
    'treat.opt2Sub': 'மலச்சிக்கல் உள்ள நோயாளிகளுக்கு',
    'treat.herbalPills': 'மூலிகை மாத்திரைகள்',
    'treat.ayurvedicSyrup': 'ஆயுர்வேத சிரப்',
    'treat.constPowder': 'மலச்சிக்கல் பொடி',
    'treat.helpBleeding': 'இரத்தப்போக்கு',
    'treat.helpPain': 'வலி',
    'treat.helpSwelling': 'பைல்ஸ் வீக்கம்',
    'treat.helpConstipation': 'மலச்சிக்கல்',
    'treat.helpPiles': 'பைல்ஸ்',
    'treat.includes': 'உள்ளடக்கியது',
    'treat.helpsIn': 'உதவுகிறது',
    'treat.codAvailable': 'கேஷ் ஆன் டெலிவரி',
    'treat.recommended': 'பரிந்துரைக்கப்பட்டது',
    'howto.title': 'மருந்தை எவ்வாறு பயன்படுத்துவது',
    'howto.pills.title': 'மாத்திரைகள்',
    'howto.pills.desc': 'தினமும் காலை 1 மாத்திரை, இரவு 1 மாத்திரை உணவுக்கு முன் எடுத்துக்கொள்ளுங்கள்.',
    'howto.syrup.title': 'சிரப்',
    'howto.syrup.desc': 'இரவு தூங்கும் முன் 10 ml சிரப் எடுத்துக்கொள்ளுங்கள்.',
    'howto.powder.title': 'பொடி',
    'howto.powder.desc': 'மலச்சிக்கல் இருந்தால், இரவு 1 தேக்கரண்டி பொடி எடுத்துக்கொள்ளுங்கள்.',
    'effect.title': 'மருந்தின் செயல்பாட்டு காலம்',
    'effect.week1': 'முதல் 3-7 நாட்கள்',
    'effect.week1desc': 'வலி, எரிச்சல் மற்றும் அரிப்பு குறைய உதவும்.',
    'effect.week2': '7-14 நாட்கள்',
    'effect.week2desc': 'இரத்தப்போக்கு மற்றும் வீக்கம் குறைய உதவும்.',
    'effect.week3': '2-4 வாரங்கள்',
    'effect.week3desc': 'பைல்ஸ் கட்டிகள் படிப்படியாக சுருங்கும்.',
    'effect.week4': '4-8 வாரங்கள்',
    'effect.week4desc': 'பைல்ஸ் அறிகுறிகளில் ஒட்டுமொத்த முன்னேற்றம்.',
    'trust.title': 'ஏன் Earth Ayurvedic?',
    'trust.patients': 'சிகிச்சை பெற்ற நோயாளிகள்',
    'trust.years': 'ஆண்டுகள் அனுபவம்',
    'trust.satisfaction': 'திருப்தி விகிதம்',
    'trust.ayurvedic': 'ஆயுர்வேதம்',
    'diet.title': 'என்ன சாப்பிடலாம், என்ன தவிர்க்கலாம்',
    'diet.eat': 'சாப்பிடலாம்',
    'diet.avoid': 'தவிர்க்கலாம்',
    'diet.eat1': 'நார்ச்சத்து உணவுகள்',
    'diet.eat2': 'நிறைய தண்ணீர் குடியுங்கள்',
    'diet.eat3': 'முழு தானியங்கள்',
    'diet.eat4': 'பப்பாளி, வாழைப்பழம்',
    'diet.eat5': 'கீரை வகைகள்',
    'diet.eat6': 'மோர் மற்றும் தயிர்',
    'diet.avoid1': 'காரமான மற்றும் எண்ணெய் உணவு',
    'diet.avoid2': 'துரித உணவு',
    'diet.avoid3': 'சிவப்பு இறைச்சி',
    'diet.avoid4': 'அதிக டீ காபி',
    'diet.avoid5': 'மது மற்றும் புகைபிடித்தல்',
    'diet.avoid6': 'மைதா பொருட்கள்',
    'stats.patients': 'வெற்றிகரமான நோயாளிகள்',
    'stats.years': 'ஆண்டுகள் நம்பிக்கை',
    'stats.delivery': 'நகரங்களில் டெலிவரி',
    'stats.satisfaction': 'திருப்தி விகிதம்',
    'reviews.title': 'எங்கள் நோயாளிகள் என்ன சொல்கிறார்கள்',
    'whatsapp.reviews': 'WhatsApp மதிப்பாய்வுகள்',
    'certificates.title': 'சான்றளிக்கப்பட்டது',
    'reels.title': 'நோயாளிகளின் கதைகள்',
    'faq.title': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'faq.q1': 'இந்த மருந்து பாதுகாப்பானதா?',
    'faq.a1': 'ஆம், இது 100% ஆயுர்வேதம் மற்றும் இயற்கை மூலிகைகளால் தயாரிக்கப்பட்டது.',
    'faq.q2': 'எத்தனை நாளில் பலன் தெரியும்?',
    'faq.a2': 'வழக்கமான பயன்பாட்டில் 7-15 நாட்களில் முன்னேற்றம் தெரியும்.',
    'faq.q3': 'COD கிடைக்குமா?',
    'faq.a3': 'ஆம், இந்தியா முழுவதும் Cash on Delivery கிடைக்கும்.',
    'faq.q4': 'பெண்கள் இந்த மருந்தை பயன்படுத்தலாமா?',
    'faq.a4': 'ஆம், ஆண்கள் மற்றும் பெண்கள் இருவருக்கும் பாதுகாப்பானது.',
    'faq.q5': 'எனக்கு 3 மருந்துகளும் தேவையா?',
    'faq.a5': 'மலச்சிக்கல் இருந்தால் முழு பேக்கேஜ் (₹1300) பரிந்துரைக்கப்படுகிறது.',
    'ordercta.title': 'நிவாரணம் பெற தயாரா?',
    'ordercta.subtitle': 'உங்கள் சிகிச்சையை தேர்ந்தெடுத்து Cash on Delivery ஆர்டர் செய்யுங்கள்',
    'order.title': 'இப்போது ஆர்டர் செய்யுங்கள்',
    'order.name': 'முழு பெயர்',
    'order.phone': 'தொலைபேசி எண்',
    'order.address': 'முழு முகவரி',
    'order.city': 'நகரம்',
    'order.state': 'மாநிலம்',
    'order.pincode': 'PIN குறியீடு',
    'order.package': 'பேக்கேஜ் தேர்வு',
    'order.pkg1': 'மாத்திரைகள் + சிரப் - ₹1000',
    'order.pkg2': 'மாத்திரைகள் + சிரப் + பொடி - ₹1300',
    'order.submit': 'ஆர்டர் செய்யுங்கள்',
    'order.cod': 'கேஷ் ஆன் டெலிவரி',
    'order.free': 'இலவச வீட்டு டெலிவரி',
    'footer.disclaimer': 'இது ஒரு ஆயுர்வேத தயாரிப்பு. முடிவுகள் மாறுபடலாம்.',
    'important.info': 'முக்கிய தகவல்',
    'constipation.title': 'பைல்ஸில் மலச்சிக்கலின் பங்கு',
    'constipation.desc': 'மலச்சிக்கல் பெரும்பாலான பைல்ஸ் பிரச்சனைகளின் மூல காரணம்.',
    'm2':'உங்களுக்கு மலச்சிக்கல் இருந்தால் மட்டும் இந்த காம்போவை எடுத்துக்கொள்ளுங்கள்',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.order': 'ఇప్పుడు ఆర్డర్ చేయండి',
    'nav.reviews': 'సమీక్షలు',
    'nav.contact': 'సంప్రదించండి',
    'hero.badge': 'నమ్మకమైన ఆయుర్వేద మందు',
    'hero.title': 'పైల్స్, మొటిమలు & ఫిస్టులా సమస్యా?',
    'hero.subtitle': 'ఆపరేషన్ లేకుండా ఆయుర్వేద చికిత్స',
    'hero.cta': 'ఇప్పుడు ఆర్డర్ చేయండి',
    'hero.ayurvedic': '100% ఆయుర్వేదం',
    'hero.patients': '3.5 లక్షల+ రోగులు',
    'hero.experience': '10+ సంవత్సరాల అనుభవం',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'పైల్స్, మొటిమలు & ఫిస్టులా అంటే ఏమిటి?',
    'problem.subtitle': 'సరైన పరిష్కారం కనుగొనడానికి సమస్యను అర్థం చేసుకోండి',
    'problem.piles': 'పైల్స్',
    'problem.pilesDesc': 'ఆసన ప్రాంతంలో వాపు సిరలు నొప్పి, మంట మరియు రక్తస్రావం కలిగిస్తాయి.',
    'problem.massa': 'మొటిమలు',
    'problem.massaDesc': 'ఆసనం బయట చిన్న మాంసం ఎదుగుదల కూర్చుంటే నొప్పి.',
    'problem.fistula': 'ఫిస్టులా',
    'problem.fistulaDesc': 'ఆసనం దగ్గర గాయం లేదా మార్గం ఏర్పడడం చీము మరియు నొప్పి.',
    'problem.symptoms': 'సాధారణ లక్షణాలు',
    'problem.sym1': 'మలవిసర్జన సమయంలో నొప్పి',
    'problem.sym2': 'రక్తస్రావం',
    'problem.sym3': 'మంట & దురద',
    'problem.sym4': 'వాపు',
    'causes.title': 'పైల్స్ ఏర్పడే ముఖ్య కారణాలు',
    'causes.cause1': 'మలబద్ధకం',
    'causes.cause2': 'మసాలా ఆహారం',
    'causes.cause3': 'ఎక్కువ సేపు కూర్చోవడం',
    'causes.cause4': 'తక్కువ నీళ్ళు తాగడం',
    'causes.cause5': 'జీర్ణక్రియ సమస్యలు',
    'solution.title': 'Earth Ayurvedic సహజ పరిష్కారం',
    'solution.combo': 'శక్తివంతమైన ఆయుర్వేద కాంబినేషన్',
    'solution.pills': 'హర్బల్ మాత్రలు',
    'solution.syrup': 'ఆయుర్వేద సిరప్',
    'solution.powder': 'మలబద్ధకం పొడి',
    'solution.b1': 'రక్తస్రావం ఆపడంలో సహాయం',
    'solution.b2': 'పైల్స్ ఎండబెట్టడంలో సహాయం',
    'solution.b3': 'నొప్పి మరియు మంట నుండి ఉపశమనం',
    'solution.b4': 'జీర్ణక్రియ మెరుగుపరచడంలో సహాయం',
    'benefits.title': 'ముఖ్య ప్రయోజనాలు',
    'benefits.pain': 'నొప్పి నివారణ',
    'benefits.bleeding': 'రక్తస్రావం ఆపుతుంది',
    'benefits.burning': 'మంట తగ్గిస్తుంది',
    'benefits.itching': 'దురద ఆపుతుంది',
    'benefits.pus': 'చీము ఆపుతుంది',
    'benefits.dryout': 'పైల్స్ ఎండబెడుతుంది',
    'benefits.lumps': 'ముద్దలు తగ్గిస్తుంది',
    'benefits.constipation': 'మలబద్ధకం నివారణ',
    'treat.title': 'సరైన చికిత్సను ఎంచుకోండి',
    'treat.opt1Title': '₹1000 చికిత్స',
    'treat.opt1Sub': 'మలబద్ధకం లేని రోగులకు',
    'treat.opt2Title': '₹1300 పూర్తి చికిత్స',
    'treat.opt2Sub': 'మలబద్ధకం ఉన్న రోగులకు',
    'treat.herbalPills': 'హర్బల్ మాత్రలు',
    'treat.ayurvedicSyrup': 'ఆయుర్వేద సిరప్',
    'treat.constPowder': 'మలబద్ధకం పొడి',
    'treat.helpBleeding': 'రక్తస్రావం',
    'treat.helpPain': 'నొప్పి',
    'treat.helpSwelling': 'పైల్స్ వాపు',
    'treat.helpConstipation': 'మలబద్ధకం',
    'treat.helpPiles': 'పైల్స్',
    'treat.includes': 'ఇందులో ఉన్నవి',
    'treat.helpsIn': 'సహాయపడుతుంది',
    'treat.codAvailable': 'క్యాష్ ఆన్ డెలివరీ',
    'treat.recommended': 'సిఫారసు',
    'howto.title': 'మందు ఎలా వాడాలి',
    'howto.pills.title': 'మాత్రలు',
    'howto.pills.desc': 'రోజూ ఉదయం 1, రాత్రి 1 మాత్ర భోజనానికి ముందు తీసుకోండి.',
    'howto.syrup.title': 'సిరప్',
    'howto.syrup.desc': 'రాత్రి నిద్రపోయే ముందు 10 ml సిరప్ తీసుకోండి.',
    'howto.powder.title': 'పొడి',
    'howto.powder.desc': 'మలబద్ధకం ఉంటే రాత్రి 1 టీస్పూన్ పొడి తీసుకోండి.',
    'effect.title': 'మందు ప్రభావ కాలం',
    'effect.week1': 'మొదటి 3-7 రోజులు',
    'effect.week1desc': 'నొప్పి, మంట మరియు దురద తగ్గడంలో సహాయం.',
    'effect.week2': '7-14 రోజులు',
    'effect.week2desc': 'రక్తస్రావం మరియు వాపు తగ్గడంలో సహాయం.',
    'effect.week3': '2-4 వారాలు',
    'effect.week3desc': 'పైల్స్ ముద్దలు క్రమంగా తగ్గడం.',
    'effect.week4': '4-8 వారాలు',
    'effect.week4desc': 'పైల్స్ లక్షణాలలో మొత్తం మెరుగుదల.',
    'trust.title': 'ఎందుకు Earth Ayurvedic?',
    'trust.patients': 'చికిత్స పొందిన రోగులు',
    'trust.years': 'సంవత్సరాల అనుభవం',
    'trust.satisfaction': 'సంతృప్తి రేటు',
    'trust.ayurvedic': 'ఆయుర్వేదం',
    'diet.title': 'ఏమి తినాలి & ఏమి తినకూడదు',
    'diet.eat': 'తినాలి',
    'diet.avoid': 'తినకూడదు',
    'diet.eat1': 'ఫైబర్ అధికంగా ఉన్న ఆహారం',
    'diet.eat2': 'ఎక్కువ నీళ్ళు తాగండి',
    'diet.eat3': 'తృణధాన్యాలు',
    'diet.eat4': 'బొప్పాయి, అరటిపండు',
    'diet.eat5': 'ఆకుకూరలు',
    'diet.eat6': 'మజ్జిగ మరియు పెరుగు',
    'diet.avoid1': 'మసాలా మరియు నూనె ఆహారం',
    'diet.avoid2': 'జంక్ ఫుడ్',
    'diet.avoid3': 'ఎర్ర మాంసం',
    'diet.avoid4': 'ఎక్కువ టీ కాఫీ',
    'diet.avoid5': 'మద్యం మరియు ధూమపానం',
    'diet.avoid6': 'మైదా ఉత్పత్తులు',
    'stats.patients': 'విజయవంతమైన రోగులు',
    'stats.years': 'సంవత్సరాల నమ్మకం',
    'stats.delivery': 'నగరాలలో డెలివరీ',
    'stats.satisfaction': 'సంతృప్తి రేటు',
    'reviews.title': 'మా రోగులు ఏం చెబుతున్నారు',
    'whatsapp.reviews': 'WhatsApp సమీక్షలు',
    'certificates.title': 'ధృవీకరించబడింది',
    'reels.title': 'రోగుల కథలు చూడండి',
    'faq.title': 'తరచుగా అడిగే ప్రశ్నలు',
    'faq.q1': 'ఈ మందు సురక్షితమా?',
    'faq.a1': 'అవును, ఇది 100% ఆయుర్వేదం మరియు సహజ మూలికలతో తయారు.',
    'faq.q2': 'ఎన్ని రోజుల్లో ఫలితం కనిపిస్తుంది?',
    'faq.a2': 'సాధారణ వాడకంతో 7-15 రోజుల్లో మెరుగుదల కనిపిస్తుంది.',
    'faq.q3': 'COD అందుబాటులో ఉందా?',
    'faq.a3': 'అవును, భారతదేశం అంతటా Cash on Delivery అందుబాటులో ఉంది.',
    'faq.q4': 'మహిళలు ఈ మందు వాడవచ్చా?',
    'faq.a4': 'అవును, పురుషులు మరియు మహిళలు ఇద్దరికీ సురక్షితం.',
    'faq.q5': 'నాకు 3 మందులు అవసరమా?',
    'faq.a5': 'మలబద్ధకం ఉంటే పూర్తి ప్యాకేజ్ (₹1300) సిఫారసు.',
    'ordercta.title': 'ఉపశమనం పొందడానికి సిద్ధంగా ఉన్నారా?',
    'ordercta.subtitle': 'మీ చికిత్సను ఎంచుకోండి మరియు Cash on Delivery ఆర్డర్ చేయండి',
    'order.title': 'ఇప్పుడు ఆర్డర్ చేయండి',
    'order.name': 'పూర్తి పేరు',
    'order.phone': 'ఫోన్ నంబర్',
    'order.address': 'పూర్తి చిరునామా',
    'order.city': 'నగరం',
    'order.state': 'రాష్ట్రం',
    'order.pincode': 'PIN కోడ్',
    'order.package': 'ప్యాకేజీ ఎంచుకోండి',
    'order.pkg1': 'మాత్రలు + సిరప్ - ₹1000',
    'order.pkg2': 'మాత్రలు + సిరప్ + పొడి - ₹1300',
    'order.submit': 'ఆర్డర్ చేయండి',
    'order.cod': 'క్యాష్ ఆన్ డెలివరీ',
    'order.free': 'ఉచిత హోమ్ డెలివరీ',
    'footer.disclaimer': 'ఇది ఒక ఆయుర్వేద ఉత్పత్తి. ఫలితాలు మారవచ్చు.',
    'important.info': 'ముఖ్యమైన సమాచారం',
    'constipation.title': 'పైల్స్‌లో మలబద్ధకం పాత్ర',
    'constipation.desc': 'మలబద్ధకం చాలా పైల్స్ సమస్యలకు మూల కారణం.',
    'm2':'మీకు మలబద్ధకం ఉంటే మాత్రమే ఈ కాంబో తీసుకోండి',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.order': 'এখনই অর্ডার করুন',
    'nav.reviews': 'রিভিউ',
    'nav.contact': 'যোগাযোগ',
    'hero.badge': 'বিশ্বস্ত আয়ুর্বেদিক ওষুধ',
    'hero.title': 'পাইলস, আঁচিল ও ফিস্টুলায় কষ্ট পাচ্ছেন?',
    'hero.subtitle': 'অপারেশন ছাড়া আয়ুর্বেদিক চিকিৎসা',
    'hero.cta': 'এখনই অর্ডার করুন',
    'hero.ayurvedic': '১০০% আয়ুর্বেদিক',
    'hero.patients': '৩.৫ লাখ+ রোগী',
    'hero.experience': '১০+ বছরের অভিজ্ঞতা',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'পাইলস, আঁচিল ও ফিস্টুলা কী?',
    'problem.subtitle': 'সঠিক সমাধান খুঁজতে সমস্যাটি বুঝুন',
    'problem.piles': 'পাইলস',
    'problem.pilesDesc': 'পায়ুর চারপাশে ফোলা শিরা যা ব্যথা, জ্বালা ও রক্তপাত ঘটায়।',
    'problem.massa': 'আঁচিল',
    'problem.massaDesc': 'পায়ুর বাইরে ছোট মাংসের বৃদ্ধি বসতে ব্যথা হয়।',
    'problem.fistula': 'ফিস্টুলা',
    'problem.fistulaDesc': 'পায়ুর কাছে ঘা বা পথ তৈরি হওয়া পুঁজ ও ব্যথা হয়।',
    'problem.symptoms': 'সাধারণ লক্ষণ',
    'problem.sym1': 'মলত্যাগে ব্যথা',
    'problem.sym2': 'রক্তপাত',
    'problem.sym3': 'জ্বালা ও চুলকানি',
    'problem.sym4': 'ফোলা',
    'causes.title': 'পাইলস হওয়ার মূল কারণ',
    'causes.cause1': 'কোষ্ঠকাঠিন্য',
    'causes.cause2': 'মশলাদার খাবার',
    'causes.cause3': 'দীর্ঘক্ষণ বসে থাকা',
    'causes.cause4': 'কম পানি পান',
    'causes.cause5': 'হজম সমস্যা',
    'solution.title': 'Earth Ayurvedic এর প্রাকৃতিক সমাধান',
    'solution.combo': 'শক্তিশালী আয়ুর্বেদিক কম্বিনেশন',
    'solution.pills': 'হার্বাল ট্যাবলেট',
    'solution.syrup': 'আয়ুর্বেদিক সিরাপ',
    'solution.powder': 'কোষ্ঠকাঠিন্য গুঁড়ো',
    'solution.b1': 'রক্তপাত বন্ধে সাহায্য',
    'solution.b2': 'পাইলস শুকাতে সাহায্য',
    'solution.b3': 'ব্যথা ও জ্বালায় উপশম',
    'solution.b4': 'হজম উন্নত করতে সাহায্য',
    'benefits.title': 'প্রধান সুবিধা',
    'benefits.pain': 'ব্যথা নিরাময়',
    'benefits.bleeding': 'রক্তপাত বন্ধ',
    'benefits.burning': 'জ্বালা কমায়',
    'benefits.itching': 'চুলকানি বন্ধ',
    'benefits.pus': 'পুঁজ বন্ধ',
    'benefits.dryout': 'পাইলস শুকায়',
    'benefits.lumps': 'গোটা কমায়',
    'benefits.constipation': 'কোষ্ঠকাঠিন্য নিরাময়',
    'treat.title': 'সঠিক চিকিৎসা বেছে নিন',
    'treat.opt1Title': '₹১০০০ চিকিৎসা',
    'treat.opt1Sub': 'কোষ্ঠকাঠিন্য ছাড়া রোগীদের জন্য',
    'treat.opt2Title': '₹১৩০০ সম্পূর্ণ চিকিৎসা',
    'treat.opt2Sub': 'কোষ্ঠকাঠিন্য সহ রোগীদের জন্য',
    'treat.herbalPills': 'হার্বাল ট্যাবলেট',
    'treat.ayurvedicSyrup': 'আয়ুর্বেদিক সিরাপ',
    'treat.constPowder': 'কোষ্ঠকাঠিন্য গুঁড়ো',
    'treat.helpBleeding': 'রক্তপাত',
    'treat.helpPain': 'ব্যথা',
    'treat.helpSwelling': 'পাইলস ফোলা',
    'treat.helpConstipation': 'কোষ্ঠকাঠিন্য',
    'treat.helpPiles': 'পাইলস',
    'treat.includes': 'অন্তর্ভুক্ত',
    'treat.helpsIn': 'সাহায্য করে',
    'treat.codAvailable': 'ক্যাশ অন ডেলিভারি',
    'treat.recommended': 'সুপারিশকৃত',
    'howto.title': 'ওষুধ কিভাবে ব্যবহার করবেন',
    'howto.pills.title': 'ট্যাবলেট',
    'howto.pills.desc': 'প্রতিদিন সকালে ১টি ও রাতে ১টি ট্যাবলেট খাবারের আগে নিন।',
    'howto.syrup.title': 'সিরাপ',
    'howto.syrup.desc': 'রাতে ঘুমানোর আগে ১০ মিলি সিরাপ নিন।',
    'howto.powder.title': 'গুঁড়ো',
    'howto.powder.desc': 'কোষ্ঠকাঠিন্য থাকলে রাতে ১ চামচ গুঁড়ো নিন।',
    'effect.title': 'ওষুধের প্রভাব সময়কাল',
    'effect.week1': 'প্রথম ৩-৭ দিন',
    'effect.week1desc': 'ব্যথা, জ্বালা ও চুলকানি কমতে সাহায্য করে।',
    'effect.week2': '৭-১৪ দিন',
    'effect.week2desc': 'রক্তপাত ও ফোলা কমতে সাহায্য করে।',
    'effect.week3': '২-৪ সপ্তাহ',
    'effect.week3desc': 'পাইলসের গোটা ধীরে ধীরে কমতে থাকে।',
    'effect.week4': '৪-৮ সপ্তাহ',
    'effect.week4desc': 'পাইলসের লক্ষণে সামগ্রিক উন্নতি।',
    'trust.title': 'কেন Earth Ayurvedic?',
    'trust.patients': 'চিকিৎসা প্রাপ্ত রোগী',
    'trust.years': 'বছরের অভিজ্ঞতা',
    'trust.satisfaction': 'সন্তুষ্টি হার',
    'trust.ayurvedic': 'আয়ুর্বেদিক',
    'diet.title': 'কী খাবেন ও কী খাবেন না',
    'diet.eat': 'খাবেন',
    'diet.avoid': 'খাবেন না',
    'diet.eat1': 'ফাইবার সমৃদ্ধ খাবার',
    'diet.eat2': 'প্রচুর পানি পান করুন',
    'diet.eat3': 'গোটা শস্য',
    'diet.eat4': 'পেঁপে, কলা',
    'diet.eat5': 'সবুজ শাকসবজি',
    'diet.eat6': 'ঘোল ও দই',
    'diet.avoid1': 'মশলাদার ও তৈলাক্ত খাবার',
    'diet.avoid2': 'জাঙ্ক ফুড',
    'diet.avoid3': 'লাল মাংস',
    'diet.avoid4': 'অতিরিক্ত চা কফি',
    'diet.avoid5': 'মদ ও ধূমপান',
    'diet.avoid6': 'ময়দা পণ্য',
    'stats.patients': 'সফল রোগী',
    'stats.years': 'বছরের বিশ্বাস',
    'stats.delivery': 'শহরে ডেলিভারি',
    'stats.satisfaction': 'সন্তুষ্টি হার',
    'reviews.title': 'আমাদের রোগীরা কী বলছেন',
    'whatsapp.reviews': 'WhatsApp রিভিউ',
    'certificates.title': 'প্রত্যয়িত ও যাচাইকৃত',
    'reels.title': 'রোগীদের গল্প দেখুন',
    'faq.title': 'সচরাচর জিজ্ঞাসিত প্রশ্ন',
    'faq.q1': 'এই ওষুধ কি নিরাপদ?',
    'faq.a1': 'হ্যাঁ, এটি ১০০% আয়ুর্বেদিক এবং প্রাকৃতিক ভেষজ দিয়ে তৈরি।',
    'faq.q2': 'কত দিনে ফলাফল দেখা যাবে?',
    'faq.a2': 'নিয়মিত ব্যবহারে ৭-১৫ দিনে উন্নতি দেখা যায়।',
    'faq.q3': 'COD পাওয়া যায়?',
    'faq.a3': 'হ্যাঁ, সারা ভারতে Cash on Delivery পাওয়া যায়।',
    'faq.q4': 'মহিলারা কি এই ওষুধ ব্যবহার করতে পারেন?',
    'faq.a4': 'হ্যাঁ, পুরুষ ও মহিলা উভয়ের জন্য নিরাপদ।',
    'faq.q5': 'আমার কি ৩টি ওষুধ দরকার?',
    'faq.a5': 'কোষ্ঠকাঠিন্য থাকলে সম্পূর্ণ প্যাকেজ (₹১৩০০) সুপারিশ করা হয়।',
    'ordercta.title': 'উপশম পেতে প্রস্তুত?',
    'ordercta.subtitle': 'আপনার চিকিৎসা বেছে নিন এবং Cash on Delivery অর্ডার করুন',
    'order.title': 'এখনই অর্ডার করুন',
    'order.name': 'পূর্ণ নাম',
    'order.phone': 'ফোন নম্বর',
    'order.address': 'সম্পূর্ণ ঠিকানা',
    'order.city': 'শহর',
    'order.state': 'রাজ্য',
    'order.pincode': 'PIN কোড',
    'order.package': 'প্যাকেজ নির্বাচন করুন',
    'order.pkg1': 'ট্যাবলেট + সিরাপ - ₹১০০০',
    'order.pkg2': 'ট্যাবলেট + সিরাপ + গুঁড়ো - ₹১৩০০',
    'order.submit': 'অর্ডার করুন',
    'order.cod': 'ক্যাশ অন ডেলিভারি',
    'order.free': 'বিনামূল্যে হোম ডেলিভারি',
    'footer.disclaimer': 'এটি একটি আয়ুর্বেদিক পণ্য। ফলাফল ভিন্ন হতে পারে।',
    'important.info': 'গুরুত্বপূর্ণ তথ্য',
    'constipation.title': 'পাইলসে কোষ্ঠকাঠিন্যের ভূমিকা',
    'constipation.desc': 'কোষ্ঠকাঠিন্য বেশিরভাগ পাইলস সমস্যার মূল কারণ।',
    'm2':'আপনার কোষ্ঠকাঠিন্য থাকলে তবেই এই কম্বোটি নিন',
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.order': 'आता ऑर्डर करा',
    'nav.reviews': 'पुनरावलोकने',
    'nav.contact': 'संपर्क',
    'hero.badge': 'विश्वसनीय आयुर्वेदिक औषध',
    'hero.title': 'मूळव्याध, मस्से आणि भगंदरने त्रस्त आहात?',
    'hero.subtitle': 'ऑपरेशनशिवाय आयुर्वेदिक उपचार',
    'hero.cta': 'आता ऑर्डर करा',
    'hero.ayurvedic': '१००% आयुर्वेदिक',
    'hero.patients': '३.५ लाख+ रुग्ण',
    'hero.experience': '१०+ वर्षांचा अनुभव',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'मूळव्याध, मस्से आणि भगंदर म्हणजे काय?',
    'problem.subtitle': 'योग्य उपाय शोधण्यासाठी समस्या समजून घ्या',
    'problem.piles': 'मूळव्याध',
    'problem.pilesDesc': 'गुदद्वाराभोवती सुजलेल्या नसा ज्यामुळे वेदना, जळजळ आणि रक्तस्त्राव होतो.',
    'problem.massa': 'मस्से',
    'problem.massaDesc': 'गुदद्वाराबाहेर लहान मांसाचा उभार ज्यामुळे बसताना वेदना होतात.',
    'problem.fistula': 'भगंदर',
    'problem.fistulaDesc': 'गुदद्वाराजवळ जखम किंवा मार्ग तयार होणे ज्यामुळे पू आणि वेदना.',
    'problem.symptoms': 'सामान्य लक्षणे',
    'problem.sym1': 'मलविसर्जनात वेदना',
    'problem.sym2': 'रक्तस्त्राव',
    'problem.sym3': 'जळजळ आणि खाज',
    'problem.sym4': 'सूज',
    'causes.title': 'मूळव्याध होण्याची मुख्य कारणे',
    'causes.cause1': 'बद्धकोष्ठता',
    'causes.cause2': 'तिखट अन्न',
    'causes.cause3': 'बराच वेळ बसणे',
    'causes.cause4': 'कमी पाणी पिणे',
    'causes.cause5': 'पचन बिघडणे',
    'solution.title': 'Earth Ayurvedic चे नैसर्गिक समाधान',
    'solution.combo': 'शक्तिशाली आयुर्वेदिक संयोजन',
    'solution.pills': 'हर्बल गोळ्या',
    'solution.syrup': 'आयुर्वेदिक सिरप',
    'solution.powder': 'बद्धकोष्ठता पावडर',
    'solution.b1': 'रक्तस्त्राव थांबवण्यास मदत',
    'solution.b2': 'मूळव्याध सुकवण्यास मदत',
    'solution.b3': 'वेदना आणि जळजळीत आराम',
    'solution.b4': 'पचन सुधारण्यास मदत',
    'benefits.title': 'मुख्य फायदे',
    'benefits.pain': 'वेदना निवारण',
    'benefits.bleeding': 'रक्तस्त्राव थांबवते',
    'benefits.burning': 'जळजळ कमी करते',
    'benefits.itching': 'खाज थांबवते',
    'benefits.pus': 'पू थांबवते',
    'benefits.dryout': 'मूळव्याध सुकवते',
    'benefits.lumps': 'गाठी कमी करते',
    'benefits.constipation': 'बद्धकोष्ठतेत आराम',
    'treat.title': 'योग्य उपचार निवडा',
    'treat.opt1Title': '₹१००० उपचार',
    'treat.opt1Sub': 'बद्धकोष्ठता नसलेल्या रुग्णांसाठी',
    'treat.opt2Title': '₹१३०० पूर्ण उपचार',
    'treat.opt2Sub': 'बद्धकोष्ठता असलेल्या रुग्णांसाठी',
    'treat.herbalPills': 'हर्बल गोळ्या',
    'treat.ayurvedicSyrup': 'आयुर्वेदिक सिरप',
    'treat.constPowder': 'बद्धकोष्ठता पावडर',
    'treat.helpBleeding': 'रक्तस्त्राव',
    'treat.helpPain': 'वेदना',
    'treat.helpSwelling': 'मूळव्याधाची सूज',
    'treat.helpConstipation': 'बद्धकोष्ठता',
    'treat.helpPiles': 'मूळव्याध',
    'treat.includes': 'समाविष्ट आहे',
    'treat.helpsIn': 'मदत करते',
    'treat.codAvailable': 'कॅश ऑन डिलिव्हरी',
    'treat.recommended': 'शिफारसकृत',
    'howto.title': 'औषध कसे वापरावे',
    'howto.pills.title': 'गोळ्या',
    'howto.pills.desc': 'रोज सकाळी १ आणि रात्री १ गोळी जेवणापूर्वी घ्या.',
    'howto.syrup.title': 'सिरप',
    'howto.syrup.desc': 'रात्री झोपण्यापूर्वी १० मिली सिरप घ्या.',
    'howto.powder.title': 'पावडर',
    'howto.powder.desc': 'बद्धकोष्ठता असल्यास रात्री १ चमचा पावडर घ्या.',
    'effect.title': 'औषधाचा प्रभाव कालावधी',
    'effect.week1': 'पहिले ३-७ दिवस',
    'effect.week1desc': 'वेदना, जळजळ आणि खाज कमी होण्यास मदत.',
    'effect.week2': '७-१४ दिवस',
    'effect.week2desc': 'रक्तस्त्राव आणि सूज कमी होण्यास मदत.',
    'effect.week3': '२-४ आठवडे',
    'effect.week3desc': 'मूळव्याधाच्या गाठी हळूहळू कमी होतात.',
    'effect.week4': '४-८ आठवडे',
    'effect.week4desc': 'मूळव्याधाच्या लक्षणांमध्ये एकूण सुधारणा.',
    'trust.title': 'का निवडा Earth Ayurvedic?',
    'trust.patients': 'उपचार केलेले रुग्ण',
    'trust.years': 'वर्षांचा अनुभव',
    'trust.satisfaction': 'समाधान दर',
    'trust.ayurvedic': 'आयुर्वेदिक',
    'diet.title': 'काय खावे आणि काय टाळावे',
    'diet.eat': 'खावे',
    'diet.avoid': 'टाळावे',
    'diet.eat1': 'फायबरयुक्त पदार्थ',
    'diet.eat2': 'भरपूर पाणी प्या',
    'diet.eat3': 'संपूर्ण धान्य',
    'diet.eat4': 'पपई, केळे',
    'diet.eat5': 'हिरव्या पालेभाज्या',
    'diet.eat6': 'ताक आणि दही',
    'diet.avoid1': 'तिखट आणि तेलकट अन्न',
    'diet.avoid2': 'जंक फूड',
    'diet.avoid3': 'लाल मांस',
    'diet.avoid4': 'जास्त चहा कॉफी',
    'diet.avoid5': 'मद्य आणि धूम्रपान',
    'diet.avoid6': 'मैदा उत्पादने',
    'stats.patients': 'यशस्वी रुग्ण',
    'stats.years': 'वर्षांचा विश्वास',
    'stats.delivery': 'शहरांमध्ये डिलिव्हरी',
    'stats.satisfaction': 'समाधान दर',
    'reviews.title': 'आमचे रुग्ण काय म्हणतात',
    'whatsapp.reviews': 'WhatsApp पुनरावलोकने',
    'certificates.title': 'प्रमाणित आणि सत्यापित',
    'reels.title': 'रुग्णांच्या कथा पहा',
    'faq.title': 'वारंवार विचारले जाणारे प्रश्न',
    'faq.q1': 'हे औषध सुरक्षित आहे का?',
    'faq.a1': 'होय, हे १००% आयुर्वेदिक आणि नैसर्गिक वनस्पतींपासून बनवलेले आहे.',
    'faq.q2': 'किती दिवसात परिणाम दिसतो?',
    'faq.a2': 'नियमित वापरात ७-१५ दिवसांत सुधारणा जाणवते.',
    'faq.q3': 'COD उपलब्ध आहे का?',
    'faq.a3': 'होय, संपूर्ण भारतात Cash on Delivery उपलब्ध आहे.',
    'faq.q4': 'महिला हे औषध वापरू शकतात का?',
    'faq.a4': 'होय, पुरुष आणि महिला दोघांसाठी सुरक्षित आहे.',
    'faq.q5': 'मला ३ औषधे लागतात का?',
    'faq.a5': 'बद्धकोष्ठता असल्यास पूर्ण पॅकेज (₹१३००) शिफारसकृत आहे.',
    'ordercta.title': 'आराम मिळवण्यास तयार आहात?',
    'ordercta.subtitle': 'तुमचा उपचार निवडा आणि Cash on Delivery ऑर्डर करा',
    'order.title': 'आता ऑर्डर करा',
    'order.name': 'पूर्ण नाव',
    'order.phone': 'फोन नंबर',
    'order.address': 'पूर्ण पत्ता',
    'order.city': 'शहर',
    'order.state': 'राज्य',
    'order.pincode': 'पिन कोड',
    'order.package': 'पॅकेज निवडा',
    'order.pkg1': 'गोळ्या + सिरप - ₹१०००',
    'order.pkg2': 'गोळ्या + सिरप + पावडर - ₹१३००',
    'order.submit': 'ऑर्डर करा',
    'order.cod': 'कॅश ऑन डिलिव्हरी',
    'order.free': 'मोफत होम डिलिव्हरी',
    'footer.disclaimer': 'हे एक आयुर्वेदिक उत्पादन आहे. परिणाम भिन्न असू शकतात.',
    'important.info': 'महत्त्वाची माहिती',
    'constipation.title': 'मूळव्याधात बद्धकोष्ठतेची भूमिका',
    'constipation.desc': 'बद्धकोष्ठता बहुतांश मूळव्याध समस्यांचे मूळ कारण आहे.',
    'm2':'तुम्हाला बद्धकोष्ठता असल्यासच हा कॉम्बो घ्या',
  },
  gu: {
    'nav.home': 'હોમ',
    'nav.order': 'હવે ઓર્ડર કરો',
    'nav.reviews': 'સમીક્ષાઓ',
    'nav.contact': 'સંપર્ક',
    'hero.badge': 'વિશ્વસનીય આયુર્વેદિક દવા',
    'hero.title': 'પાઈલ્સ, મસા અને ભગંદરથી પરેશાન છો?',
    'hero.subtitle': 'ઓપરેશન વગર આયુર્વેદિક ઈલાજ',
    'hero.cta': 'હવે ઓર્ડર કરો',
    'hero.ayurvedic': '૧૦૦% આયુર્વેદિક',
    'hero.patients': '૩.૫ લાખ+ દર્દીઓ',
    'hero.experience': '૧૦+ વર્ષનો અનુભવ',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'પાઈલ્સ, મસા અને ભગંદર શું છે?',
    'problem.subtitle': 'સાચો ઉકેલ શોધવા સમસ્યા સમજો',
    'problem.piles': 'પાઈલ્સ',
    'problem.pilesDesc': 'ગુદા આસપાસ સોજેલી નસો જેનાથી દર્દ, બળતરા અને લોહી વહે છે.',
    'problem.massa': 'મસા',
    'problem.massaDesc': 'ગુદા બહાર માંસનો નાનો ઉભાર જેનાથી બેસવામાં દર્દ થાય છે.',
    'problem.fistula': 'ભગંદર',
    'problem.fistulaDesc': 'ગુદા પાસે ઘા કે રસ્તો બનવો જેનાથી પરુ અને દર્દ થાય છે.',
    'problem.symptoms': 'સામાન્ય લક્ષણો',
    'problem.sym1': 'મળત્યાગમાં દર્દ',
    'problem.sym2': 'લોહી વહેવું',
    'problem.sym3': 'બળતરા અને ખંજવાળ',
    'problem.sym4': 'સોજો',
    'causes.title': 'પાઈલ્સ થવાના મુખ્ય કારણો',
    'causes.cause1': 'કબજિયાત',
    'causes.cause2': 'મસાલેદાર ભોજન',
    'causes.cause3': 'લાંબો સમય બેસવું',
    'causes.cause4': 'ઓછું પાણી પીવું',
    'causes.cause5': 'પાચન ખરાબ થવું',
    'solution.title': 'Earth Ayurvedic નો કુદરતી ઉકેલ',
    'solution.combo': 'શક્તિશાળી આયુર્વેદિક સંયોજન',
    'solution.pills': 'હર્બલ ગોળીઓ',
    'solution.syrup': 'આયુર્વેદિક સીરપ',
    'solution.powder': 'કબજિયાત પાવડર',
    'solution.b1': 'રક્તસ્ત્રાવ બંધ કરવામાં મદદ',
    'solution.b2': 'પાઈલ્સ સુકવવામાં મદદ',
    'solution.b3': 'દર્દ અને બળતરામાં રાહત',
    'solution.b4': 'પાચન સુધારવામાં મદદ',
    'benefits.title': 'મુખ્ય ફાયદા',
    'benefits.pain': 'દર્દ રાહત',
    'benefits.bleeding': 'રક્તસ્ત્રાવ બંધ',
    'benefits.burning': 'બળતરા ઘટાડે',
    'benefits.itching': 'ખંજવાળ બંધ',
    'benefits.pus': 'પરુ બંધ',
    'benefits.dryout': 'પાઈલ્સ સુકવે',
    'benefits.lumps': 'ગાંઠ ઘટાડે',
    'benefits.constipation': 'કબજિયાત રાહત',
    'treat.title': 'સાચો ઈલાજ પસંદ કરો',
    'treat.opt1Title': '₹૧૦૦૦ ઈલાજ',
    'treat.opt1Sub': 'કબજિયાત વગરના દર્દીઓ માટે',
    'treat.opt2Title': '₹૧૩૦૦ પૂર્ણ ઈલાજ',
    'treat.opt2Sub': 'કબજિયાત વાળા દર્દીઓ માટે',
    'treat.herbalPills': 'હર્બલ ગોળીઓ',
    'treat.ayurvedicSyrup': 'આયુર્વેદિક સીરપ',
    'treat.constPowder': 'કબજિયાત પાવડર',
    'treat.helpBleeding': 'રક્તસ્ત્રાવ',
    'treat.helpPain': 'દર્દ',
    'treat.helpSwelling': 'પાઈલ્સ સોજો',
    'treat.helpConstipation': 'કબજિયાત',
    'treat.helpPiles': 'પાઈલ્સ',
    'treat.includes': 'સમાવિષ્ટ',
    'treat.helpsIn': 'મદદ કરે છે',
    'treat.codAvailable': 'કેશ ઓન ડિલિવરી',
    'treat.recommended': 'ભલામણ',
    'howto.title': 'દવા કેવી રીતે વાપરવી',
    'howto.pills.title': 'ગોળીઓ',
    'howto.pills.desc': 'રોજ સવારે ૧ અને રાત્રે ૧ ગોળી જમતા પહેલા લો.',
    'howto.syrup.title': 'સીરપ',
    'howto.syrup.desc': 'રાત્રે સૂતા પહેલા ૧૦ મિલી સીરપ લો.',
    'howto.powder.title': 'પાવડર',
    'howto.powder.desc': 'કબજિયાત હોય તો રાત્રે ૧ ચમચી પાવડર લો.',
    'effect.title': 'દવાની અસર અવધિ',
    'effect.week1': 'પ્રથમ ૩-૭ દિવસ',
    'effect.week1desc': 'દર્દ, બળતરા અને ખંજવાળ ઓછી થવામાં મદદ.',
    'effect.week2': '૭-૧૪ દિવસ',
    'effect.week2desc': 'રક્તસ્ત્રાવ અને સોજો ઓછો થવામાં મદદ.',
    'effect.week3': '૨-૪ અઠવાડિયા',
    'effect.week3desc': 'પાઈલ્સની ગાંઠ ધીરે ધીરે ઓછી થવા લાગે.',
    'effect.week4': '૪-૮ અઠવાડિયા',
    'effect.week4desc': 'પાઈલ્સના લક્ષણોમાં સમગ્ર સુધારો.',
    'trust.title': 'શા માટે Earth Ayurvedic?',
    'trust.patients': 'ઈલાજ કરેલા દર્દીઓ',
    'trust.years': 'વર્ષનો અનુભવ',
    'trust.satisfaction': 'સંતોષ દર',
    'trust.ayurvedic': 'આયુર્વેદિક',
    'diet.title': 'શું ખાવું અને શું ન ખાવું',
    'diet.eat': 'ખાવું',
    'diet.avoid': 'ન ખાવું',
    'diet.eat1': 'ફાઈબરયુક્ત ખોરાક',
    'diet.eat2': 'પુષ્કળ પાણી પીવો',
    'diet.eat3': 'આખા ધાન',
    'diet.eat4': 'પપૈયા, કેળા',
    'diet.eat5': 'લીલા શાકભાજી',
    'diet.eat6': 'છાશ અને દહીં',
    'diet.avoid1': 'મસાલેદાર અને તેલવાળો ખોરાક',
    'diet.avoid2': 'જંક ફૂડ',
    'diet.avoid3': 'લાલ માંસ',
    'diet.avoid4': 'વધારે ચા કોફી',
    'diet.avoid5': 'દારૂ અને ધૂમ્રપાન',
    'diet.avoid6': 'મેંદા ઉત્પાદનો',
    'stats.patients': 'સફળ દર્દીઓ',
    'stats.years': 'વર્ષનો વિશ્વાસ',
    'stats.delivery': 'શહેરોમાં ડિલિવરી',
    'stats.satisfaction': 'સંતોષ દર',
    'reviews.title': 'અમારા દર્દીઓ શું કહે છે',
    'whatsapp.reviews': 'WhatsApp સમીક્ષાઓ',
    'certificates.title': 'પ્રમાણિત અને ચકાસાયેલ',
    'reels.title': 'દર્દીઓની વાતો જુઓ',
    'faq.title': 'વારંવાર પૂછાતા પ્રશ્નો',
    'faq.q1': 'આ દવા સુરક્ષિત છે?',
    'faq.a1': 'હા, આ ૧૦૦% આયુર્વેદિક અને કુદરતી જડીબુટ્ટીઓથી બનેલી છે.',
    'faq.q2': 'કેટલા દિવસમાં અસર દેખાશે?',
    'faq.a2': 'નિયમિત ઉપયોગથી ૭-૧૫ દિવસમાં સુધારો દેખાય છે.',
    'faq.q3': 'COD ઉપલબ્ધ છે?',
    'faq.a3': 'હા, આખા ભારતમાં Cash on Delivery ઉપલબ્ધ છે.',
    'faq.q4': 'મહિલાઓ આ દવા વાપરી શકે?',
    'faq.a4': 'હા, પુરુષો અને મહિલાઓ બંને માટે સુરક્ષિત છે.',
    'faq.q5': 'શું મારે ૩ દવાઓ જોઈએ?',
    'faq.a5': 'કબજિયાત હોય તો પૂર્ણ પેકેજ (₹૧૩૦૦) ભલામણ છે.',
    'ordercta.title': 'રાહત મેળવવા તૈયાર છો?',
    'ordercta.subtitle': 'તમારો ઈલાજ પસંદ કરો અને Cash on Delivery ઓર્ડર કરો',
    'order.title': 'હવે ઓર્ડર કરો',
    'order.name': 'પૂરું નામ',
    'order.phone': 'ફોન નંબર',
    'order.address': 'પૂરું સરનામું',
    'order.city': 'શહેર',
    'order.state': 'રાજ્ય',
    'order.pincode': 'PIN કોડ',
    'order.package': 'પેકેજ પસંદ કરો',
    'order.pkg1': 'ગોળીઓ + સીરપ - ₹૧૦૦૦',
    'order.pkg2': 'ગોળીઓ + સીરપ + પાવડર - ₹૧૩૦૦',
    'order.submit': 'ઓર્ડર કરો',
    'order.cod': 'કેશ ઓન ડિલિવરી',
    'order.free': 'મફત હોમ ડિલિવરી',
    'footer.disclaimer': 'આ એક આયુર્વેદિક ઉત્પાદન છે. પરિણામો અલગ હોઈ શકે છે.',
    'important.info': 'મહત્વપૂર્ણ માહિતી',
    'constipation.title': 'પાઈલ્સમાં કબજિયાતની ભૂમિકા',
    'constipation.desc': 'કબજિયાત મોટાભાગની પાઈલ્સ સમસ્યાઓનું મૂળ કારણ છે.',
    'm2': 'આ કોમ્બો માત્ર ત્યારે લો જ્યારે તમને કબજિયાત હોય',
  },
  pa: {
    'nav.home': 'ਹੋਮ',
    'nav.order': 'ਹੁਣੇ ਆਰਡਰ ਕਰੋ',
    'nav.reviews': 'ਸਮੀਖਿਆਵਾਂ',
    'nav.contact': 'ਸੰਪਰਕ',
    'hero.badge': 'ਭਰੋਸੇਮੰਦ ਆਯੁਰਵੈਦਿਕ ਦਵਾ',
    'hero.title': 'ਬਵਾਸੀਰ, ਮੱਸੇ ਅਤੇ ਭਗੰਦਰ ਤੋਂ ਪਰੇਸ਼ਾਨ ਹੋ?',
    'hero.subtitle': 'ਬਿਨਾਂ ਆਪਰੇਸ਼ਨ ਆਯੁਰਵੈਦਿਕ ਇਲਾਜ',
    'hero.cta': 'ਹੁਣੇ ਆਰਡਰ ਕਰੋ',
    'hero.ayurvedic': '੧੦੦% ਆਯੁਰਵੈਦਿਕ',
    'hero.patients': '੩.੫ ਲੱਖ+ ਮਰੀਜ਼',
    'hero.experience': '੧੦+ ਸਾਲ ਦਾ ਤਜ਼ਰਬਾ',
    'hero.cod': 'Cash on Delivery',
    'problem.title': 'ਬਵਾਸੀਰ, ਮੱਸੇ ਅਤੇ ਭਗੰਦਰ ਕੀ ਹੈ?',
    'problem.subtitle': 'ਸਹੀ ਹੱਲ ਲੱਭਣ ਲਈ ਸਮੱਸਿਆ ਸਮਝੋ',
    'problem.piles': 'ਬਵਾਸੀਰ',
    'problem.pilesDesc': 'ਗੁਦਾ ਦੇ ਆਲੇ-ਦੁਆਲੇ ਸੁੱਜੀਆਂ ਨਸਾਂ ਜਿਸ ਨਾਲ ਦਰਦ, ਜਲਣ ਅਤੇ ਖੂਨ ਆਉਂਦਾ ਹੈ.',
    'problem.massa': 'ਮੱਸੇ',
    'problem.massaDesc': 'ਗੁਦਾ ਦੇ ਬਾਹਰ ਮਾਸ ਦਾ ਛੋਟਾ ਉਭਾਰ ਜਿਸ ਨਾਲ ਬੈਠਣ ਵਿੱਚ ਦਰਦ.',
    'problem.fistula': 'ਭਗੰਦਰ',
    'problem.fistulaDesc': 'ਗੁਦਾ ਕੋਲ ਜ਼ਖ਼ਮ ਜਾਂ ਰਾਹ ਬਣ ਜਾਣਾ ਜਿਸ ਨਾਲ ਪੱਸ ਅਤੇ ਦਰਦ.',
    'problem.symptoms': 'ਆਮ ਲੱਛਣ',
    'problem.sym1': 'ਮਲ ਤਿਆਗ ਵੇਲੇ ਦਰਦ',
    'problem.sym2': 'ਖੂਨ ਆਉਣਾ',
    'problem.sym3': 'ਜਲਣ ਅਤੇ ਖੁਜਲੀ',
    'problem.sym4': 'ਸੋਜ',
    'causes.title': 'ਬਵਾਸੀਰ ਹੋਣ ਦੇ ਮੁੱਖ ਕਾਰਨ',
    'causes.cause1': 'ਕਬਜ਼',
    'causes.cause2': 'ਮਸਾਲੇਦਾਰ ਖਾਣਾ',
    'causes.cause3': 'ਲੰਬੇ ਸਮੇਂ ਤੱਕ ਬੈਠਣਾ',
    'causes.cause4': 'ਘੱਟ ਪਾਣੀ ਪੀਣਾ',
    'causes.cause5': 'ਪਾਚਨ ਖ਼ਰਾਬ ਹੋਣਾ',
    'solution.title': 'Earth Ayurvedic ਦਾ ਕੁਦਰਤੀ ਹੱਲ',
    'solution.combo': 'ਸ਼ਕਤੀਸ਼ਾਲੀ ਆਯੁਰਵੈਦਿਕ ਸੰਯੋਜਨ',
    'solution.pills': 'ਹਰਬਲ ਗੋਲੀਆਂ',
    'solution.syrup': 'ਆਯੁਰਵੈਦਿਕ ਸਿਰਪ',
    'solution.powder': 'ਕਬਜ਼ ਪਾਊਡਰ',
    'solution.b1': 'ਖੂਨ ਬੰਦ ਕਰਨ ਵਿੱਚ ਮਦਦ',
    'solution.b2': 'ਬਵਾਸੀਰ ਸੁਕਾਉਣ ਵਿੱਚ ਮਦਦ',
    'solution.b3': 'ਦਰਦ ਅਤੇ ਜਲਣ ਵਿੱਚ ਰਾਹਤ',
    'solution.b4': 'ਪਾਚਨ ਸੁਧਾਰਨ ਵਿੱਚ ਮਦਦ',
    'benefits.title': 'ਮੁੱਖ ਫਾਇਦੇ',
    'benefits.pain': 'ਦਰਦ ਰਾਹਤ',
    'benefits.bleeding': 'ਖੂਨ ਬੰਦ',
    'benefits.burning': 'ਜਲਣ ਘਟਾਏ',
    'benefits.itching': 'ਖੁਜਲੀ ਬੰਦ',
    'benefits.pus': 'ਪੱਸ ਬੰਦ',
    'benefits.dryout': 'ਬਵਾਸੀਰ ਸੁਕਾਏ',
    'benefits.lumps': 'ਗੰਢ ਘਟਾਏ',
    'benefits.constipation': 'ਕਬਜ਼ ਰਾਹਤ',
    'treat.title': 'ਸਹੀ ਇਲਾਜ ਚੁਣੋ',
    'treat.opt1Title': '₹੧੦੦੦ ਇਲਾਜ',
    'treat.opt1Sub': 'ਕਬਜ਼ ਤੋਂ ਬਿਨਾਂ ਮਰੀਜ਼ਾਂ ਲਈ',
    'treat.opt2Title': '₹੧੩੦੦ ਪੂਰਾ ਇਲਾਜ',
    'treat.opt2Sub': 'ਕਬਜ਼ ਵਾਲੇ ਮਰੀਜ਼ਾਂ ਲਈ',
    'treat.herbalPills': 'ਹਰਬਲ ਗੋਲੀਆਂ',
    'treat.ayurvedicSyrup': 'ਆਯੁਰਵੈਦਿਕ ਸਿਰਪ',
    'treat.constPowder': 'ਕਬਜ਼ ਪਾਊਡਰ',
    'treat.helpBleeding': 'ਖੂਨ',
    'treat.helpPain': 'ਦਰਦ',
    'treat.helpSwelling': 'ਬਵਾਸੀਰ ਸੋਜ',
    'treat.helpConstipation': 'ਕਬਜ਼',
    'treat.helpPiles': 'ਬਵਾਸੀਰ',
    'treat.includes': 'ਸ਼ਾਮਲ ਹੈ',
    'treat.helpsIn': 'ਮਦਦ ਕਰਦਾ ਹੈ',
    'treat.codAvailable': 'ਕੈਸ਼ ਆਨ ਡਿਲੀਵਰੀ',
    'treat.recommended': 'ਸੁਝਾਅ',
    'howto.title': 'ਦਵਾਈ ਕਿਵੇਂ ਵਰਤਣੀ ਹੈ',
    'howto.pills.title': 'ਗੋਲੀਆਂ',
    'howto.pills.desc': 'ਰੋਜ਼ ਸਵੇਰੇ ੧ ਅਤੇ ਰਾਤ ਨੂੰ ੧ ਗੋਲੀ ਖਾਣੇ ਤੋਂ ਪਹਿਲਾਂ ਲਓ.',
    'howto.syrup.title': 'ਸਿਰਪ',
    'howto.syrup.desc': 'ਰਾਤ ਨੂੰ ਸੌਣ ਤੋਂ ਪਹਿਲਾਂ ੧੦ ਮਿਲੀ ਸਿਰਪ ਲਓ.',
    'howto.powder.title': 'ਪਾਊਡਰ',
    'howto.powder.desc': 'ਕਬਜ਼ ਹੋਵੇ ਤਾਂ ਰਾਤ ਨੂੰ ੧ ਚਮਚ ਪਾਊਡਰ ਲਓ.',
    'effect.title': 'ਦਵਾਈ ਦੇ ਪ੍ਰਭਾਵ ਦੀ ਮਿਆਦ',
    'effect.week1': 'ਪਹਿਲੇ ੩-੭ ਦਿਨ',
    'effect.week1desc': 'ਦਰਦ, ਜਲਣ ਅਤੇ ਖੁਜਲੀ ਘੱਟ ਹੋਣ ਵਿੱਚ ਮਦਦ.',
    'effect.week2': '੭-੧੪ ਦਿਨ',
    'effect.week2desc': 'ਖੂਨ ਅਤੇ ਸੋਜ ਘੱਟ ਹੋਣ ਵਿੱਚ ਮਦਦ.',
    'effect.week3': '੨-੪ ਹਫ਼ਤੇ',
    'effect.week3desc': 'ਬਵਾਸੀਰ ਦੀ ਗੰਢ ਹੌਲੀ ਹੌਲੀ ਘੱਟ ਹੋਣ ਲੱਗਦੀ ਹੈ.',
    'effect.week4': '੪-੮ ਹਫ਼ਤੇ',
    'effect.week4desc': 'ਬਵਾਸੀਰ ਦੇ ਲੱਛਣਾਂ ਵਿੱਚ ਸਮੁੱਚਾ ਸੁਧਾਰ.',
    'trust.title': 'ਕਿਉਂ ਚੁਣੋ Earth Ayurvedic?',
    'trust.patients': 'ਇਲਾਜ ਕੀਤੇ ਮਰੀਜ਼',
    'trust.years': 'ਸਾਲ ਦਾ ਤਜ਼ਰਬਾ',
    'trust.satisfaction': 'ਸੰਤੁਸ਼ਟੀ ਦਰ',
    'trust.ayurvedic': 'ਆਯੁਰਵੈਦਿਕ',
    'diet.title': 'ਕੀ ਖਾਣਾ ਅਤੇ ਕੀ ਨਹੀਂ ਖਾਣਾ',
    'diet.eat': 'ਖਾਣਾ',
    'diet.avoid': 'ਨਹੀਂ ਖਾਣਾ',
    'diet.eat1': 'ਫਾਈਬਰ ਵਾਲਾ ਭੋਜਨ',
    'diet.eat2': 'ਬਹੁਤ ਪਾਣੀ ਪੀਓ',
    'diet.eat3': 'ਸਾਬਤ ਅਨਾਜ',
    'diet.eat4': 'ਪਪੀਤਾ, ਕੇਲਾ',
    'diet.eat5': 'ਹਰੀਆਂ ਸਬਜ਼ੀਆਂ',
    'diet.eat6': 'ਲੱਸੀ ਅਤੇ ਦਹੀ',
    'diet.avoid1': 'ਮਸਾਲੇਦਾਰ ਅਤੇ ਤੇਲੀ ਭੋਜਨ',
    'diet.avoid2': 'ਜੰਕ ਫੂਡ',
    'diet.avoid3': 'ਲਾਲ ਮੀਟ',
    'diet.avoid4': 'ਜ਼ਿਆਦਾ ਚਾਹ ਕੌਫੀ',
    'diet.avoid5': 'ਸ਼ਰਾਬ ਅਤੇ ਸਿਗਰਟ',
    'diet.avoid6': 'ਮੈਦਾ ਉਤਪਾਦ',
    'stats.patients': 'ਸਫ਼ਲ ਮਰੀਜ਼',
    'stats.years': 'ਸਾਲ ਦਾ ਭਰੋਸਾ',
    'stats.delivery': 'ਸ਼ਹਿਰਾਂ ਵਿੱਚ ਡਿਲੀਵਰੀ',
    'stats.satisfaction': 'ਸੰਤੁਸ਼ਟੀ ਦਰ',
    'reviews.title': 'ਸਾਡੇ ਮਰੀਜ਼ ਕੀ ਕਹਿੰਦੇ ਹਨ',
    'whatsapp.reviews': 'WhatsApp ਸਮੀਖਿਆਵਾਂ',
    'certificates.title': 'ਪ੍ਰਮਾਣਿਤ ਅਤੇ ਤਸਦੀਕਸ਼ੁਦਾ',
    'reels.title': 'ਮਰੀਜ਼ਾਂ ਦੀਆਂ ਕਹਾਣੀਆਂ ਦੇਖੋ',
    'faq.title': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
    'faq.q1': 'ਕੀ ਇਹ ਦਵਾ ਸੁਰੱਖਿਅਤ ਹੈ?',
    'faq.a1': 'ਹਾਂ, ਇਹ ੧੦੦% ਆਯੁਰਵੈਦਿਕ ਅਤੇ ਕੁਦਰਤੀ ਜੜੀ-ਬੂਟੀਆਂ ਤੋਂ ਬਣੀ ਹੈ.',
    'faq.q2': 'ਕਿੰਨੇ ਦਿਨਾਂ ਵਿੱਚ ਅਸਰ ਦਿਖੇਗਾ?',
    'faq.a2': 'ਨਿਯਮਿਤ ਵਰਤੋਂ ਨਾਲ ੭-੧੫ ਦਿਨਾਂ ਵਿੱਚ ਸੁਧਾਰ ਮਹਿਸੂਸ ਹੁੰਦਾ ਹੈ.',
    'faq.q3': 'ਕੀ COD ਉਪਲਬਧ ਹੈ?',
    'faq.a3': 'ਹਾਂ, ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ Cash on Delivery ਉਪਲਬਧ ਹੈ.',
    'faq.q4': 'ਕੀ ਔਰਤਾਂ ਇਹ ਦਵਾ ਵਰਤ ਸਕਦੀਆਂ ਹਨ?',
    'faq.a4': 'ਹਾਂ, ਮਰਦਾਂ ਅਤੇ ਔਰਤਾਂ ਦੋਵਾਂ ਲਈ ਸੁਰੱਖਿਅਤ ਹੈ.',
    'faq.q5': 'ਕੀ ਮੈਨੂੰ ੩ ਦਵਾਈਆਂ ਚਾਹੀਦੀਆਂ ਹਨ?',
    'faq.a5': 'ਕਬਜ਼ ਹੋਵੇ ਤਾਂ ਪੂਰਾ ਪੈਕੇਜ (₹੧੩੦੦) ਸੁਝਾਅ ਹੈ.',
    'ordercta.title': 'ਰਾਹਤ ਪਾਉਣ ਲਈ ਤਿਆਰ ਹੋ?',
    'ordercta.subtitle': 'ਆਪਣਾ ਇਲਾਜ ਚੁਣੋ ਅਤੇ Cash on Delivery ਆਰਡਰ ਕਰੋ',
    'order.title': 'ਹੁਣੇ ਆਰਡਰ ਕਰੋ',
    'order.name': 'ਪੂਰਾ ਨਾਮ',
    'order.phone': 'ਫ਼ੋਨ ਨੰਬਰ',
    'order.address': 'ਪੂਰਾ ਪਤਾ',
    'order.city': 'ਸ਼ਹਿਰ',
    'order.state': 'ਰਾਜ',
    'order.pincode': 'PIN ਕੋਡ',
    'order.package': 'ਪੈਕੇਜ ਚੁਣੋ',
    'order.pkg1': 'ਗੋਲੀਆਂ + ਸਿਰਪ - ₹੧੦੦੦',
    'order.pkg2': 'ਗੋਲੀਆਂ + ਸਿਰਪ + ਪਾਊਡਰ - ₹੧੩੦੦',
    'order.submit': 'ਆਰਡਰ ਕਰੋ',
    'order.cod': 'ਕੈਸ਼ ਆਨ ਡਿਲੀਵਰੀ',
    'order.free': 'ਮੁਫ਼ਤ ਹੋਮ ਡਿਲੀਵਰੀ',
    'footer.disclaimer': 'ਇਹ ਇੱਕ ਆਯੁਰਵੈਦਿਕ ਉਤਪਾਦ ਹੈ. ਨਤੀਜੇ ਵੱਖ ਹੋ ਸਕਦੇ ਹਨ.',
    'important.info': 'ਮਹੱਤਵਪੂਰਨ ਜਾਣਕਾਰੀ',
    'constipation.title': 'ਬਵਾਸੀਰ ਵਿੱਚ ਕਬਜ਼ ਦੀ ਭੂਮਿਕਾ',
    'constipation.desc': 'ਕਬਜ਼ ਜ਼ਿਆਦਾਤਰ ਬਵਾਸੀਰ ਸਮੱਸਿਆਵਾਂ ਦਾ ਮੂਲ ਕਾਰਨ ਹੈ.',
    'm2':'ਇਹ ਕੰਬੋ ਸਿਰਫ਼ ਉਸ ਵੇਲੇ ਲਵੋ ਜੇ ਤੁਹਾਨੂੰ ਕਬਜ਼ ਹੋਵੇ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('hi');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
